### ISSUE TITLE
JavaScript vs TypeScript

### ISSUE THREAD

**Issue by fourstacks** [CodeHubOrg/codehub-mentorships#4]
@CodeHubOrg/codehub-mentorships 

I was hoping we can come to a collective decision on whether to use TypeScript or just plain JavaScript in this project.  I'm pretty torn on the issue and I don't want to end up pushing the project in a direction that's contrary to most peoples preferences - particularly given that there's a lot of interest in the React side of the project.

From my perspective these are the pros and cons of using TypeScript over JavaScript

Pros:

- Enforces a level of consistency and data integrity at a code level
- Is an industry favourite so good experience for those looking for work
- We have at least 3 people on the project with decent TypeScript experience

Cons:

- Compiler errors can be pretty daunting/frustrating, particularly for those just getting to grips with using terminal
- It's an extra layer of syntax and convention to learn which could hamper understanding of more basic JavaScript concepts

I'm sure there are probably other arguments for and against.  I'd really love to get peoples votes on this so if you could sound off below on whether you want to use TS on this project or not I'd be very grateful - I'll go with the majority opinion and close voting on Wednesday evening.

**Comment by AlisonYoon** [comment]
I would definitely vote for using TypeScript not because I know it well but because all the great comments I heard from people who are using it :)

**Comment by katjad** [comment]
I would keep the project JavaScript only, but there could be small parts of the app written in TypeScript for those who want to use or learn it?

**Comment by fourstacks** [comment]
Hey everyone - just to let you know that we've opted to go for TypeScript over plain JavaScript.  There are enough people currently interested in developing the project that have enough experience with TS that we can help out those with less exposure to TypeScript
